name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libssl-dev libgest-dev libgmock-dev valgrind
    - name: Configure
      run: |
        cmake -B build -D CMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build build
    - name: Unit Test
      run: |
        cmake --build build --target test
    - name: Memcheck
      working-directory: build
      run: |
        valgrind --error-exitcode=1 ./alltests
